#define BBLIBC_LIB_EXPORT
#include "Vararg.h"
#include "MessageManager.h"
#include "MessageChannel.h"
#include <stdio.h>


static char Dest[1024];

/*
* Module:                 BBLibc.dll
* Data address:           0x1004A53C
* VC++ mangling:          ?mout@@3VB_MessageManager@@A
*/
#ifndef BLD_NATIVE
B_MessageManager mout;
#endif


/*
* Module:                 BBLibc.dll
* Entry point:            0x10002710
* VC++ mangling:          ??1B_MessageManager@@QAE@XZ
*/
#ifndef BLD_NATIVE
B_MessageManager::~B_MessageManager()
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10029BE0
* VC++ mangling:          ?vararg@@YAPBDPBDZZ
*/

const char *vararg(const char *format, ...)
{
    va_list args;
    va_start(args, format);

    vsprintf(Dest, format, args);

    va_end(args);

    return Dest;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x10029CFC
* VC++ mangling:          ?Add@B_MessageManager@@QAEIPAVB_MessageChannel@@@Z
*/
#ifndef BLD_NATIVE
unsigned int B_MessageManager::Add(B_MessageChannel *channel)
{
    return 0;
}
#endif


/*
* Module:                 BBLibc.dll
* Entry point:            0x10029E17
* VC++ mangling:          ?OpenChannel@B_MessageManager@@QAEIABVB_Name@@@Z
*/
#ifndef BLD_NATIVE
unsigned int B_MessageManager::OpenChannel(const B_Name &channel_name)
{
    return 0;
}
#endif


/*
* Module:                 BBLibc.dll
* Entry point:            0x10029E98
* VC++ mangling:          ?CloseChannel@B_MessageManager@@QAEIABVB_Name@@@Z
*/
#ifndef BLD_NATIVE
unsigned int B_MessageManager::CloseChannel(const B_Name &channel_name)
{
    return 1;
}
#endif


/*
* Module:                 BBLibc.dll
* Entry point:            0x10029F19
* VC++ mangling:          ?DisconnectChannel@B_MessageManager@@QAEPAVB_MessageChannel@@ABVB_Name@@@Z
*/
#ifndef BLD_NATIVE
B_MessageChannel *B_MessageManager::DisconnectChannel(const B_Name &channel_name)
{
    return nullptr;
}
#endif

/*
*
* Implicit definition of virtual method table for B_MessageChannel.
* Generated by compiler.
*
* Module:                 BBLibc.dll
* Data address:           0x10042180
* VC++ mangling:          ??_7B_MessageChannel@@6B@
*/


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A26A
* VC++ mangling:          ?Open@B_MessageChannel@@UAEIXZ
*/

unsigned int B_MessageChannel::Open()
{
    return 0;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A277
* VC++ mangling:          ?Close@B_MessageChannel@@UAEIXZ
*/

unsigned int B_MessageChannel::Close()
{
    return 0;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A284
* VC++ mangling:          ?Message@B_MessageChannel@@UAEIPBD@Z
*/

unsigned int B_MessageChannel::Message(const char *message)
{
    return 0;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A2C3
* VC++ mangling:          ??6@YAAAVB_MessageManager@@AAV0@PBD@Z
*/
#ifndef BLD_NATIVE
B_MessageManager &operator<<(B_MessageManager &mout, const char *str)
{
    return mout;
}
#endif

