
#ifndef B_LIST_H
#define B_LIST_H

// #include <bld_system.h>

#ifdef BBLIBC_LIB_EXPORT
#define BUILD_LIB
#endif
#include <export.h>
#undef BUILD_LIB

class B_List;

class LIB_EXP B_ListElement
{
public:

    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10002EA0
    * VC++ mangling:          ??0B_ListElement@@QAE@XZ
    */

    B_ListElement()
    :
        list(nullptr),
        next(nullptr),
        prev(nullptr)
    {
    }


    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10002F00
    * VC++ mangling:          ?GetNext@B_ListElement@@QAEPAV1@XZ
    */

    B_ListElement *GetNext()
    {
        return this->next;
    }


    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10002F20
    * VC++ mangling:          ?GetPrev@B_ListElement@@QAEPAV1@XZ
    */

    B_ListElement *GetPrev()
    {
        return this->prev;
    }


    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10002F40
    * VC++ mangling:          ??0B_ListElement@@QAE@ABV0@@Z
    */

    B_ListElement(const B_ListElement &other)
    :
        list(other.list),
        next(other.next),
        prev(other.prev)
    {
    }

    virtual ~B_ListElement();

    B_ListElement &operator =(const B_ListElement &other);

    B_List *GetList();

    B_List *list;
    B_ListElement *next;
    B_ListElement *prev;
};

class LIB_EXP B_List
{
public:
    B_List(B_ListElement *element);
    B_List(B_List const&);

    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x100030E0
    * VC++ mangling:          ??1B_List@@UAE@XZ
    */

    virtual ~B_List()
    {
    }


    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10003100
    * VC++ mangling:          ?nElements@B_List@@QAEIXZ
    */
#ifndef BLD_NATIVE
    unsigned int nElements()
    {
        return 0;
    }
#else
    unsigned int nElements();
#endif

    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10003120
    * VC++ mangling:          ?GetFirst@B_List@@QAEPAVB_ListElement@@XZ
    */
#ifndef BLD_NATIVE
    B_ListElement *GetFirst()
    {
        return nullptr;
    }
#else
    B_ListElement *GetFirst();
#endif

    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x10003140
    * VC++ mangling:          ?GetLast@B_List@@QAEPAVB_ListElement@@XZ
    */
#ifndef BLD_NATIVE
    B_ListElement *GetLast()
    {
        return nullptr;
    }
#else
    B_ListElement *GetLast();
#endif

    /*
    * Module:                 BBLibc.dll
    * Entry point:            0x100031A0
    * VC++ mangling:          ??4B_List@@QAEAAV0@ABV0@@Z
    */

    B_List &operator =(const B_List &that)
    {
        this->numElements = that.numElements;
        this->tail = that.tail;
        this->head = that.head;
        return *this;
    }


    /*
    *
    * Implicit definition of default constructor closure.
    * Generated by compiler.
    *
    * Module:                 BBLibc.dll
    * Entry point:            0x100031E0
    * VC++ mangling:          ??_FB_List@@QAEXXZ
    */
#ifndef BLD_NATIVE
#endif
    void DeleteList(unsigned int arg_1);
    unsigned int Add(B_ListElement *element);
    unsigned int AddAfter(B_ListElement *existing, B_ListElement *newElement);
    unsigned int AddBefore(B_ListElement *existing, B_ListElement *newElement);
    unsigned int Remove(B_ListElement *element, unsigned int index);
    B_ListElement *RemoveFirst(unsigned int arg_1);
    B_ListElement *RemoveLast(unsigned int arg_1);
    B_ListElement *GetAt(unsigned int arg_1);
    unsigned int Exists(const B_ListElement *element);

private:
    int numElements;
    B_ListElement *tail;
    B_ListElement *head;
};

#endif  // B_LIST_H
