#define BBLIBC_LIB_EXPORT
#include "MessageChannel.h"


/*
*
* Implicit definition of virtual method table for B_MessageChannel.
* Generated by compiler.
*
* Module:                 BBLibc.dll
* Data address:           0x10042180
* VC++ mangling:          ??_7B_MessageChannel@@6B@
*/


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A26A
* VC++ mangling:          ?Open@B_MessageChannel@@UAEIXZ
*/

unsigned int B_MessageChannel::Open()
{
    return 0;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A277
* VC++ mangling:          ?Close@B_MessageChannel@@UAEIXZ
*/

unsigned int B_MessageChannel::Close()
{
    return 0;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A284
* VC++ mangling:          ?Message@B_MessageChannel@@UAEIPBD@Z
*/

unsigned int B_MessageChannel::Message(const char *message)
{
    return 0;
}

/*
* Module:                 BBLibc.dll
* Entry point:            0x1002A293
* VC++ mangling:          ?Message@B_MessageManager@@QAEIDABVB_Name@@@Z
*/
#ifndef BLD_NATIVE
unsigned int B_MessageManager::Message(char arg_1, const B_Name &arg_2)
{
    return 0;
}
#endif
