#define BBLIBC_LIB_EXPORT
#include "NamedObj.h"


/*
*
* Implicit definition of virtual method table for B_NamedObj.
* Generated by compiler.
*
* Module:                 BBLibc.dll
* Data address:           0x1004217C
* VC++ mangling:          ??_7B_NamedObj@@6B@
*/


/*
* Module:                 BBLibc.dll
* Entry point:            0x100039E5
* VC++ mangling:          ??0B_NamedObj@@QAE@XZ
*/

B_NamedObj::B_NamedObj() : name() {}


/*
* Module:                 BBLibc.dll
* Entry point:            0x10003A07
* VC++ mangling:          ??0B_NamedObj@@QAE@ABVB_Name@@@Z
*/

B_NamedObj::B_NamedObj(const B_Name& n) : name(n) {}


/*
* Module:                 BBLibc.dll
* Entry point:            0x10002300
* VC++ mangling:          ??1B_NamedObj@@UAE@XZ
*/

B_NamedObj::~B_NamedObj()
{
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x10003A2F
* VC++ mangling:          ?Id@B_NamedObj@@QBEABVB_Name@@XZ
*/

const B_Name& B_NamedObj::Id() const
{
    return name;
}

