
#ifndef B_O_DATA_FILE_H

#define B_O_DATA_FILE_H

#ifdef BBLIBC_LIB_EXPORT
#define BUILD_LIB
#endif
#include <export.h>
#undef BUILD_LIB

#define OFILE_CACHE_SIZE 0x4000

class LIB_EXP B_ODataFile
{
public:
    B_ODataFile(const char *file_name, int flags);
    ~B_ODataFile();
    void Write(const void *data, unsigned int size);
    unsigned int OK() const;


    /*
    *
    * Default implementation of "B_ODataFile &operator=(const B_ODataFile&)".
    * Generated by compiler.
    *
    * Module:                 BBLibc.dll
    * Entry point:            0x10002290
    * VC++ mangling:          ??4B_ODataFile@@QAEAAV0@ABV0@@Z
    */

private:
    int fd;
    char *file_name;
    char fileCache[OFILE_CACHE_SIZE];
    unsigned int cacheBlockStartPos;
    unsigned int posInCacheBlock;
};


LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const char &c);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const char *c);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const unsigned char &c);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const short &s);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const unsigned short &s);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const int &i);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const long &l);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const unsigned long &l);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const unsigned int &i);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const float &f);
LIB_EXP B_ODataFile &operator <<(B_ODataFile &file, const double &f);


#endif /* B_O_DATA_FILE_H */

