
#ifndef B_PAL_H

#define B_PAL_H

#include <bld_system.h>

#ifdef BBLIBC_LIB_EXPORT
#define BUILD_LIB
#endif
#include <export.h>
#undef BUILD_LIB

class LIB_EXP B_Pal
{
public:
    unsigned char GetRed(unsigned int val) const;
    unsigned char GetGreen(unsigned int val) const;
    unsigned char GetBlue(unsigned int val) const;
    void SetRed(unsigned int arg_1, unsigned char arg_2);
    void SetGreen(unsigned int arg_1, unsigned char arg_2);
    void SetBlue(unsigned int arg_1, unsigned char arg_2);
    unsigned int GetIndex(
        unsigned char arg_1,
        unsigned char arg_2,
        unsigned char arg_3,
        unsigned int arg_4
    );
    const B_Pal &Id();

    /*
    *
    * Default implementation of "B_Pal &operator=(const B_Pal&)".
    * Generated by compiler.
    *
    * Module:                 BBLibc.dll
    * Entry point:            0x10006BF0
    * VC++ mangling:          ??4B_Pal@@QAEAAV0@ABV0@@Z
    */

private:
    byte data[768];
};

#endif /* B_PAL_H */
