#define BBLIBC_LIB_EXPORT
#include "Resource.h"
#include "ResourceManager.h"


/*
*
* Implicit definition of virtual method table for B_Resource.
* Generated by compiler.
*
* Module:                 BBLibc.dll
* Data address:           0x10042198
* VC++ mangling:          ??_7B_Resource@@6B@
*/

/*
* Module:                 BBLibc.dll
* Data address:           0x1004A118
* VC++ mangling:          ?B_resource_manager@@3VB_ResourceManager@@A
*/
#ifndef BLD_NATIVE
B_ResourceManager B_resource_manager;
#endif


/*
* Module:                 BBLibc.dll
* Entry point:            0x10003EB0
* VC++ mangling:          ?GetResourceManager@@YAPAVB_ResourceManager@@XZ
*/

B_ResourceManager *GetResourceManager()
{
    return &B_resource_manager;
}


/*
* Module:                 BBLibc.dll
* Entry point:            0x10003EBA
* VC++ mangling:          ??0B_Resource@@QAE@XZ
*/
#ifndef BLD_NATIVE
B_Resource::B_Resource()
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10003ED9
* VC++ mangling:          ??0B_Resource@@QAE@ABVB_Name@@@Z
*/
#ifndef BLD_NATIVE
B_Resource::B_Resource(const B_Name &arg_1)
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10003EFE
* VC++ mangling:          ??1B_Resource@@UAE@XZ
*/
#ifndef BLD_NATIVE
B_Resource::~B_Resource()
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10003F26
* VC++ mangling:          ?Save@B_Resource@@SAXAAVB_ODataFile@@PBV1@@Z
*/
#ifndef BLD_NATIVE
void B_Resource::Save(B_ODataFile &arg_1, const B_Resource *arg_2)
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10003FCE
* VC++ mangling:          ?Load@B_Resource@@SAPAV1@AAVB_IDataFile@@G@Z
*/
#ifndef BLD_NATIVE
B_Resource *B_Resource::Load(B_IDataFile &arg_1, unsigned short arg_2)
{
    return nullptr;
}
#endif
