#define BBLIBC_LIB_EXPORT
#include "Resource.h"


/*
*
* Implicit definition of virtual method table for B_Resource.
* Generated by compiler.
*
* Module:                 BBLibc.dll
* Data address:           0x10042198
* VC++ mangling:          ??_7B_Resource@@6B@
*/


/*
* Module:                 BBLibc.dll
* Entry point:            0x10003EBA
* VC++ mangling:          ??0B_Resource@@QAE@XZ
*/
#ifndef BLD_NATIVE
B_Resource::B_Resource()
{
}
#endif

/*
* Module:                 BBLibc.dll
* Entry point:            0x10003EFE
* VC++ mangling:          ??1B_Resource@@UAE@XZ
*/
#ifndef BLD_NATIVE
B_Resource::~B_Resource()
{
}
#endif
